name: Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-26.04 # need python >= 3.13 for configparser.UNNAMED_SECTION
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Build
        run: |
          pip install -r requirements.txt
          python3 parse.py
      - name: Copy files
        run: mv static out; cp out.html out/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
